config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :dramas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dramas#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drama.rb
class Drama < ApplicationRecord
	belongs_to :user
	has_attached_file :image, styles: { medium: "400x600#"}
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :dramas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dramas_controller.rb
class DramasController < ApplicationController
  before_action :set_drama, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /dramas
  # GET /dramas.json
  def index
    @dramas = Drama.all
  end

  # GET /dramas/1
  # GET /dramas/1.json
  def show
  end

  # GET /dramas/new
  def new
    @drama = current_user.dramas.build
  end

  # GET /dramas/1/edit
  def edit
  end

  # POST /dramas
  # POST /dramas.json
  def create
    @drama = current_user.dramas.build(drama_params)

    respond_to do |format|
      if @drama.save
        format.html { redirect_to @drama, notice: 'Drama was successfully created.' }
        format.json { render :show, status: :created, location: @drama }
      else
        format.html { render :new }
        format.json { render json: @drama.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dramas/1
  # PATCH/PUT /dramas/1.json
  def update
    respond_to do |format|
      if @drama.update(drama_params)
        format.html { redirect_to @drama, notice: 'Drama was successfully updated.' }
        format.json { render :show, status: :ok, location: @drama }
      else
        format.html { render :edit }
        format.json { render json: @drama.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dramas/1
  # DELETE /dramas/1.json
  def destroy
    @drama.destroy
    respond_to do |format|
      format.html { redirect_to dramas_url, notice: 'Drama was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drama
      @drama = Drama.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drama_params
      params.require(:drama).permit(:title, :description, :episode, :director, :actor, :rating, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dramas_helper.rb
module DramasHelper
end

app/views/dramas/_form.html.erb
<%= form_for @drama, html: { multipart: true } do |f| %>
  <% if @drama.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@drama.errors.count, "error") %> prohibited this drama from being saved:</h2>

      <ul>
      <% @drama.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :episode %>
    <%= f.number_field :episode %>
  </div>

  <div class="field">
    <%= f.label :director %>
    <%= f.text_field :director %>
  </div>

  <div class="field">
    <%= f.label :actor %>
    <%= f.text_field :actor %>
  </div>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image%>

  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dramas/edit.html.erb
<h1>Editing Drama</h1>

<%= render 'form', drama: @drama %>

<%= link_to 'Show', @drama %> |
<%= link_to 'Back', dramas_path %>

app/views/dramas/index.html.erb
<% if !user_signed_in? %>
  <div class="jumbotron">
    <h1>Track your favorite dramas today!</h1>
    <p>Start logging the dramas you've been watching. Never forget which episode you left off on again!</p>
    <p><%= link_to "Sign Up Now", new_user_registration_path, class:"btn btn-primary btn-lg" %></p>
<% end %>


<div class="row">
  <% @dramas.each do |drama| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag drama.image.url(:medium), class: 'image'), drama %>
      </div>
    </div>
  <% end %>
</div>

app/views/dramas/new.html.erb
<h1>New Drama</h1>

<%= render 'form', drama: @drama %>

<%= link_to 'Back', dramas_path %>

app/views/dramas/show.html.erb
<div class="panel panel-default">
  <div class="panel panel-body">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @drama.image.url(:medium) %>
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td><strong>Title:</strong></td>
                <td><%= @drama.title %></td>
              </tr>
              <tr>
                <td><strong>Description:</strong></td>
                <td><%= @drama.description %></td>
              </tr>
              <tr>
                <td><strong>Episodes:</strong></td>
                <td><%= @drama.episode %></td>
              </tr>
              <tr>
                <td><strong>Director:</strong></td>
                <td><%= @drama.director %></td>
              </tr>
              <tr>
                <td><strong>Actors:</strong></td>
                <td><%= @drama.actor %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<% if user_signed_in? %>
  <%= link_to 'Edit', edit_drama_path(@drama), class: "btn btn-default" %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "DramaLog", root_path, class: "navbar-brand" %>
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<% if user_signed_in? %>
					<li><%= link_to "New Drama", new_drama_path, class: "active" %></li>
					<li><%= link_to "Account", edit_user_registration_path %></li>
				<% else %>
					<li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
					<li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>
				<% end %>
			</ul>
			<form class="navbar-form navbar-right" role="search">
				<div class="form-group">
					<input type="text" class="form-control" placeholder="Search">
				</div>
				<button type="submit" class="btn btn-default">Submit</button>
			</form>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DramaLog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <body>
    <%= render 'layouts/header' %>
    <div class="container">
  		<% flash.each do |name, msg| %>
  			<%= content_tag(:div, msg, class: "alert alert-info") %>
  		<% end %>
    	<%= yield %>
    </div>
  </body>
</html>